version: "3"
services:
  postgres:
    container_name: shared-fridge
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/shared-fridge
    env_file:
      - docker.env
